### ISSUE TITLE
Remove KIMA non-aligned list

### ISSUE THREAD

**Issue by sinairusinek** [Hist-ME/URIs#14]
I deleted on my branch the list which I aligned with VIAF and moved to the Aligned KIMA folder. Not sure how to create pull request for deleted files.

**Comment by nathangibson** [comment]
@sinairusinek No problem, by committing to your branch, from which you had already created a pull request, it includes the deletions. All commits you make to that branch will be included in the pull request until it is merged. 

After I merge it, you can always do another pull request from the same branch to merge in new changes.

#13
