### ISSUE TITLE
URIs for DiJeSt Persons

### ISSUE THREAD

**Issue by nathangibson** [Hist-ME/URIs#6]
Hi @sinairusinek 

2495 persons aligned with VIAF = very cool!

Do you have resolvable URIs (not just ids) for DiJeSt persons that you could include in https://github.com/Hist-ME/URIs/blob/master/persons/aligned-uris/DiJeSt_personalities2VIAF.tsv ? Or if they aren't yet resolvable, at least URIs that are reserved? E.g., will DiJeSt242 be something like http://dijest.net/person/242 ? 

Also some of the lines (e.g. https://github.com/Hist-ME/URIs/blob/master/persons/aligned-uris/DiJeSt_personalities2VIAF.tsv#L15) only have `DiJeSt` without an id number.

**Comment by sinairusinek** [comment]
thanks Nathan! I updated the file so that the first column now contains the uri (usable for sparql queries)and added a url to the national library's authority files. Also got rid of the empty lines - have to check what happened there!

**Comment by nathangibson** [comment]
@sinairusinek Did you really mean to delete your whole file of non-aligned persons?
